language: python
python: 3.4

env:
  - TOXENV=py34
  - TOXENV=pep8
  - TOXENV=packaging

install: pip install tox coverage

script:
  - tox
  - coverage report --fail-under 100 > /dev/null

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#caremad"
    use_notice: true
    skip_join: true
